title: Divyaprabha M # your name (or website title) here
logo: "/images/me3.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  "When you want something, all the universe conspires in helping you to achieve it." 
  -Paulo Cohelo, Alchemist
  <br><br>
  I am a highly motivated student with a goal-driven work ethic. I have a strong curiosity for Computer Vision, 
  Machine learning and I am well versed in Statistics. 
  <br><br>
  Having interned in Bosch I had the opportunity to experience real data science workflow and I learned a lot from 
  understanding a business problem, collecting and cleaning the data, to finally building an efficient model.
  <br><br>
  <a href="https://www.linkedin.com/in/divyaprabha-m">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
